name: Ping Tests

on: workflow_dispatch

jobs:
  test-site:
    name: Execute Nerine Tests
    runs-on: ubuntu-latest
    env:
      NERINE_LICENSE: ${{ secrets.NERINE_LICENSE_KEY }}

    steps:
    - uses: actions/checkout@v6

    - name: Download Nerine
      run: |
        curl -L -o nerine-ent_linux_amd64.tar.gz https://lcisec.dev/download/nerine-ent/linux/amd64/${{ secrets.NERINE_LICENSE_ID }}
        tar -xvzf nerine-ent_linux_amd64.tar.gz

    - name: Verify Nerine
      run: |
        sudo apt install -y minisign
        minisign -Vm nerine-ent_linux_amd64 -P ${{ vars.NERINE_PUBLIC_KEY }}

    - name: Execute Binary
      run: |
        ./nerine-ent_linux_amd64 -s https://www.lcisec.com tests/up.txt
        ./nerine-ent_linux_amd64 -S targets.txt tests/up.txt
